### ISSUE TITLE
Add cookie as information for the dashboard

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/website-kumquat#90]
In the dashboard login process, we want to distinguish between users that come through the website and those who directly end up on gitpod. The latter is a common case, because of all the gitpod buttons out there.

Those who come to us without context need a bit of information, while those who have seen the website don't and should get a clean login screen. (see below the two different screens).

The website should add the cookie (`gitpod-user=loggedIn`)  to tell the app that the user has context.

## New Users without Context

<img width="1703" alt="Screenshot 2021-03-29 at 17 45 34" src="https://user-images.githubusercontent.com/372735/112864947-9b5ede00-90b8-11eb-9000-4ec18ad297c7.png">

## (New) Users with Context

<img width="1127" alt="Screenshot 2021-03-29 at 17 59 50" src="https://user-images.githubusercontent.com/372735/112864923-96019380-90b8-11eb-8078-a2331508564e.png">

**Comment by mikenikles** [comment]
Implemented in #165 and tested in an incognito browser window.
